### ISSUE TITLE
Hanging when setting up Smart DNS

### ISSUE THREAD

**Issue by jnnngs** [suuhm/unblock-proxy.sh#2]
Hi,

Great script and thanks for sharing. I'm setting up on Ubuntu 18.04.6 LTS and testing in Smart DNS mode. The script keeps hanging when performing the "ping domain" to check is up or not. It seems random as if it hangs on a domain and I remove the domain from the domain list, it sometimes hangs on one earlier that previously was okay.

Example output:

[*] Setting up iface IN -> (eth0) and OUT -> (eth0) <==> (202.61.230.XX)

[X] Killing process: tor:
[X] Killing process: squid:
[X] Killing process: privoxy:
[X] Killing process: redsocks:
[X] Killing process: proxychains:
[X] Killing process: sniproxy:
[X] Killing process: dnsmasq:

[*] Re-Setting all IPTable-Entries...

[*] Blacklist found at /opt/unblock-proxy.sh/domains.lst
[~ 1] Testing Proxy: XXXXXXXX http [seems to work :)]
[*] FOUND! (XXXXXXX)

[*] Setup SMART DNS PROXY
-> Setting up Hostname: myip.is
-> Setting up Hostname: ifconfig.co
-> Setting up Hostname: edgecastcdn.net
ping: cloudfront.net: No address associated with hostname
!! cloudfront.net seems to be down. Not set
-> Setting up Hostname: cloudfront.net
ping: zattoohds-a.akamaihd.net: Name or service not known
!! zattoohds-a.akamaihd.net seems to be down. Not set
-> Setting up Hostname: zattoohds-a.akamaihd.net
ping: zathdslive-a.akamaihd.net: Name or service not known
!! zathdslive-a.akamaihd.net seems to be down. Not set
-> Setting up Hostname: zathdslive-a.akamaihd.net
-> Setting up Hostname: zahs.tv
ping: zatsslive-a.akamaihd.net: Name or service not known
!! zatsslive-a.akamaihd.net seems to be down. Not set
-> Setting up Hostname: zatsslive-a.akamaihd.net
-> Setting up Hostname: chromecast-receiver.zattoo.com

Its hanging at this point.

Any ideas what I am doing wrong or anything to trry?

thanks in advance :)

**Comment by jnnngs** [comment]
UPDATE

Installed on a different VPS and it works. It seems the other VPS provider (netcup) is restricting outbound ping requests?

**Comment by suuhm** [comment]
yepp this could be a problem by your vps privider, can you test for example pinging cloudfront.net with an other DNS server or Proxy?
you can also test by installing nmap and do a `nmap -sP cloudfront.net` make also sure your iptables are fully flushed.

**Comment by jnnngs** [comment]
Thanks buddy, I'll give it a go. Assuming my VPS provider is performing some type of filtering, do you recommend a known working VPS provider?

**Comment by suuhm** [comment]
yeah, I think kamatera.com is a good one , so you can choose country IP where it host, for example swiss or america etc.
So , also AWS or google-cloud are worth trying too.
