### ISSUE TITLE
Error on Squid Install Script

### ISSUE THREAD

**Issue by cstrassmair** [suuhm/unblock-proxy.sh#4]
Hello!

I am trying to use your cool Script
But on installation of Squid from the Script it ends with errors

Here are the Last Lines with errors

Can you help me out?

Thanks 
Christoph

/bin/bash ./repl_modules.sh lru > repl_modules.cc
make  all-recursive
make[2]: Entering directory '/root/squid4/squid-4.13/src'
Making all in mem
make[3]: Entering directory '/root/squid4/squid-4.13/src/mem'
depbase=`echo old_api.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -DDEFAULT_CONFIG_FILE=\"/usr/local/squid/etc/squid.conf\" -DDEFAULT_SQUID_DATA_DIR=\"/usr/local/squid/share\" -DDEFAULT_SQUID_CONFIG_DIR=\"/usr/local/squid/etc\"   -I../.. -I../../include -I../../lib -I../../src -I../../include   -I../../libltdl  -Wall -Wpointer-arith -Wwrite-strings -Wcomments -Wshadow -Woverloaded-virtual -Werror -pipe -D_REENTRANT -g -O2 -march=native -MT old_api.lo -MD -MP -MF $depbase.Tpo -c -o old_api.lo old_api.cc &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -DDEFAULT_CONFIG_FILE=\"/usr/local/squid/etc/squid.conf\" -DDEFAULT_SQUID_DATA_DIR=\"/usr/local/squid/share\" -DDEFAULT_SQUID_CONFIG_DIR=\"/usr/local/squid/etc\" -I../.. -I../../include -I../../lib -I../../src -I../../include -I../../libltdl -Wall -Wpointer-arith -Wwrite-strings -Wcomments -Wshadow -Woverloaded-virtual -Werror -pipe -D_REENTRANT -g -O2 -march=native -MT old_api.lo -MD -MP -MF .deps/old_api.Tpo -c old_api.cc  -fPIC -DPIC -o .libs/old_api.o
In file included from ../../src/security/Session.h:14,
                 from ../../src/security/forward.h:14,
                 from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
../../src/security/forward.h: In function ‘void Security::DH_free_cpp(DH*)’:
../../src/security/LockingPointer.h:34:21: error: ‘void DH_free(DH*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   34 |             function(a); \
../../src/security/forward.h:85:1: note: in expansion of macro ‘CtoCpp1’
   85 | CtoCpp1(DH_free, DH *);
      | ^~~~~~~
In file included from ../../compat/openssl.h:33,
                 from ../../src/security/Context.h:15,
                 from ../../src/security/forward.h:13,
                 from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
/usr/include/openssl/dh.h:200:28: note: declared here
  200 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
In file included from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
../../src/security/forward.h: At global scope:
../../src/security/forward.h:86:70: error: ‘int DH_up_ref(DH*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   86 | typedef Security::LockingPointer<DH, DH_free_cpp, HardFun<int, DH *, DH_up_ref> > DhePointer;
      |                                                                      ^~~~~~~~~
In file included from ../../compat/openssl.h:33,
                 from ../../src/security/Context.h:15,
                 from ../../src/security/forward.h:13,
                 from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
/usr/include/openssl/dh.h:201:27: note: declared here
  201 | OSSL_DEPRECATEDIN_3_0 int DH_up_ref(DH *dh);
      |                           ^~~~~~~~~
In file included from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
../../src/security/forward.h:86:79: error: ‘int DH_up_ref(DH*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   86 | typedef Security::LockingPointer<DH, DH_free_cpp, HardFun<int, DH *, DH_up_ref> > DhePointer;
      |                                                                               ^
In file included from ../../compat/openssl.h:33,
                 from ../../src/security/Context.h:15,
                 from ../../src/security/forward.h:13,
                 from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
/usr/include/openssl/dh.h:201:27: note: declared here
  201 | OSSL_DEPRECATEDIN_3_0 int DH_up_ref(DH *dh);
      |                           ^~~~~~~~~
In file included from ../../src/ssl/support.h:21,
                 from ../../src/SquidConfig.h:24,
                 from old_api.cc:24:
../../src/ssl/gadgets.h:60:51: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   60 | typedef std::unique_ptr<RSA, HardFun<void, RSA*, &RSA_free>> RSA_Pointer;
      |                                                   ^~~~~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from ../../compat/openssl.h:42,
                 from ../../src/security/Context.h:15,
                 from ../../src/security/forward.h:13,
                 from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
In file included from ../../src/ssl/support.h:21,
                 from ../../src/SquidConfig.h:24,
                 from old_api.cc:24:
../../src/ssl/gadgets.h:60:51: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   60 | typedef std::unique_ptr<RSA, HardFun<void, RSA*, &RSA_free>> RSA_Pointer;
      |                                                   ^~~~~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from ../../compat/openssl.h:42,
                 from ../../src/security/Context.h:15,
                 from ../../src/security/forward.h:13,
                 from ../../src/SquidConfig.h:21,
                 from old_api.cc:24:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:833: old_api.lo] Error 1
make[3]: Leaving directory '/root/squid4/squid-4.13/src/mem'
make[2]: *** [Makefile:7128: all-recursive] Error 1
make[2]: Leaving directory '/root/squid4/squid-4.13/src'
make[1]: *** [Makefile:6138: all] Error 2
make[1]: Leaving directory '/root/squid4/squid-4.13/src'
make: *** [Makefile:586: all-recursive] Error 1

**Comment by suuhm** [comment]
It seems your ssl is deprecated so the squid source is also not up to date. I will try to check this the next time.
But first you can try with an other source like openssl 1.1.1j or openssl v.3.0.2?
