### ISSUE TITLE
 Apache2 Ubuntu Default Page 

### ISSUE THREAD

**Issue by zarvan9** [suuhm/unblock-proxy.sh#7]
Hello. All the domains that I added to the list only redirect to the  "Apache2 Ubuntu Default Page" . Did I make a mistake somewhere?

**Comment by suuhm** [comment]
Hi , have you some more info here please?

Can you give some output of you shell? Which os are you using etc.

Thanks

**Comment by zarvan9** [comment]
Thank you for your response.
I am using Ubuntu 20 form OVH. I have tested both Tor and Redsocks. After setting up, I use the command "unblock-proxy.sh dns -r -W" to finish the configuration. The process involves checking the proxy, adding domains, and finally showing the server IP as DNS.
But after setting the server IP as DNS in the client, all the domains that are listed are redirected to the default Apache page.

This log is generated using Tor:
unblock-proxy.sh dns --tor

https://justpaste.it/26pyn

**Comment by suuhm** [comment]
Maybe you can stop your webserver apache and try again?

Can you also pls give an output from `netstat -tulpen | egrep "80|443"`
